## set on true to enable 1.8 combat ##
old_combat: true

## /verify <admin_passwort> to be able to enter admin commands ##
admin_password: example

## protection time at game start in minutes ##
prot_time: 45

## radius for spawn flight ##
spawnradius: 50

## amount of allowed deaths ##
lives: 3

## is it allowed to respawn in beds if you have lifes left ##
bed_respawn: false

## after this amount of minutes, the worldborder starts shrinking ##
start_shrinking: 60

## worldborder radius at start of the game ##
wordborder_radius: 5000

## smallest worldborder radius ##
min_worldborder_radius: 100

## player limit per team ##
max_team_players: 2

## set the spawn by using /varos setspawn ##

~Varos Plugin by _itznosehad_
